language: python
sudo: false
python: '3.5'

cache: pip

before_install:
  - pip install --upgrade pip setuptools

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - pylama chat
  - lizard chat -C 10 -w -i 0
  - python setup.py test

notifications:
  slack:
    secure: "o58p47bhXtPO0fke13QwuSZCAS8+SWyHMHSF009XZUy5LL3CXun0dXoRXh0LyXl5BhrHxxkuZRgvuS7N+gf18AKR7ffsByaV5BwGdlQm2xrNdLWfoOGVy6R99ZBz8unO66kDuD7rKHaAn0LD2j0uy07Ekiv7Vr7n5C0CZ33XjCompTeMEmyh1Eq2XpjcF0oIzfYWzMqpbivdsbme9FIkKp4ulHv2VY8/gBMiZD1/fx8tCBU6Db/tGOWhOV/1D03qsYaAYFNHkn+RfDq/YI/jWO3dFzArBGsFgvSbqu39pvmcunFhIkT28FSIHvAVCyYIAMxDGoH33lklMhQKo7VqTksjgqjNGJZMkTMTURAjLGy3U8MvuiKq42cl+06uqYcxPm4emx8aclkIKgKfzzWh4sLBhErKWitsZXttai8+/PI0K0lAjxZ6ke75/KYg/d6RJaCkGppgMSjVkuLI0c4bNgg//PVdtC6c4RCpnUDYyKIHkTRmhQgwpXZuPzXQPe3eELuImtwaq7+bKu9CdDSb1vhjMwd6NU5nbQQZcXHSkAMrZ95rU9Kyc1hFN8kLmX6UJHyJJ2td6o4bCfyGeHQFaC35GagcK/qnqe3Lefh/XqkladdAPfgl0lJ63s/TdCYKntQrUbM7FwPoEpMgaStOox4jopdtxHwJ6ssRWl7XdBA="
